-- CATEGORIES INSERTS
INSERT INTO dbo.CATEGORIES VALUES ('Informatique');
INSERT INTO dbo.CATEGORIES VALUES ('Vêtement');
INSERT INTO dbo.CATEGORIES VALUES ('Jouet');
INSERT INTO dbo.CATEGORIES VALUES ('Décoration');
INSERT INTO dbo.CATEGORIES VALUES ('Meuble');
INSERT INTO dbo.CATEGORIES VALUES ('Autre');